 Hi there, I'm Ashit with a growth-minded Data Scientist with strong technical skills in Python, Machine Learning, NLP, Deep Learning and over seven years of experience in telecom, health insurance, financial service domain to help business grow and add value.


<!--
**Ashit-cloud/Ashit-cloud** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
